### ISSUE TITLE
Fix spec and acceptance tests

### ISSUE THREAD

**Issue by chelnak** [puppetlabs/puppetlabs-satellite_pe_tools#172]
# Context

It looks like the spec and acceptance tests have been failing for quite some time now. We should apply a bit of elbow grease so that everything starts running nicely again. It will make the integration of new contributions (such as #171 ) a lot easier and cleaner.

# Tasks

- [ ] Identify cause of failure for spec tests
- [ ] Identify cause of failure for acceptance test
- [ ] Apply fixes to spec tests
- [ ] Apply fixes to acceptance tests
- [ ] Review whether the current configuration for actions is sufficient and is in line with our other modules

**Comment by david22swan** [comment]
https://tickets.puppetlabs.com/browse/IAC-1764

**Comment by chelnak** [comment]
@david22swan Who owns artifactory?

**Comment by david22swan** [comment]
Release Engineering

**Comment by david22swan** [comment]
Have managed to track down the files, where moved onto the IAC GCP account, both the satellite and websphere files are there, not sure if we've lost anything but can't see anything missing from my perspective.

**Comment by david22swan** [comment]
PR to give satellite access to cloud storage does not seem to have worked:
https://github.com/puppetlabs/provision_service/pull/337

**Comment by pmcmaw** [comment]
@david22swan after follow up with @binford2k, it turns out we have valid credentials in OnePassword to allow us to download the new satellite images.

**Comment by david22swan** [comment]
Files downloaded and uploaded to the Artifactory and the GCP cloud storage:

- https://artifactory.delivery.puppetlabs.net/artifactory/webapp/#/artifacts/browse/simple/General/generic__local/module_ci_resources/carl
- https://console.cloud.google.com/storage/browser/artifactory-modules;tab=objects?forceOnBucketsSortingFiltering=false&project=ia-content&prefix=&forceOnObjectsSortingFiltering=false
